api/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import BlogPostViewSet

router = DefaultRouter()
router.register('posts', BlogPostViewSet, basename='blogpost')

urlpatterns = [
    # path('api-auth/', include('rest_framework.urls')),
    path('', include(router.urls)),    
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('register/', views.UserRegistrationView.as_view(), name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('my-blog/', views.MyBlogView.as_view(), name='myblog'),
    path('add-blog/', views.AddBlogView.as_view(), name='addblog'),
    path('blog-detail/<slug:the_slug>', views.BlogDetailView.as_view(), name='blogdetail'),
    path('edit-blog/<int:pk>', views.EditBlogView.as_view(), name='editblog'),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('', include('blog.urls')),
    path('api/', include('api.urls')),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/models.py
from django.db import models
from django.contrib.auth.models import User

class created_updated(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

class BlogPost(created_updated):
    title = models.CharField(max_length=200, unique=True)
    subtitle = models.CharField(max_length=255, blank=True)
    slug = models.SlugField(max_length=255, unique=True)
    image = models.ImageField(upload_to='blogs/', blank=True)
    body = models.TextField(blank=True, null=True)
    meta_description = models.CharField(max_length=150, blank=True)
    meta_keyword = models.CharField(max_length=150, blank=True)    
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, related_name='categories_post', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

blog/models.py
from django.db import models

# Create your models here.

api/views.py
from rest_framework import generics, permissions
from rest_framework_simplejwt.views import TokenObtainPairView
from .models import BlogPost
from .serializers import BlogPostSerializer
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated
from .permissions import ExcludeAuthenticationForGetMethod
from rest_framework_simplejwt.authentication import JWTAuthentication

class BlogPostViewSet(viewsets.ModelViewSet):
    serializer_class = BlogPostSerializer
    queryset = BlogPost.objects.all()
    authentication_classes = [JWTAuthentication]
    permission_classes = [IsAuthenticated]

blog/views.py
from django.shortcuts import render,redirect, get_object_or_404
from rest_framework.views import APIView
from rest_framework.response import Response
from .serializers import UserRegistrationSerializer, UserLoginSerializer
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from api.models import BlogPost, Category
from django.urls import resolve
from rest_framework_simplejwt.tokens import RefreshToken


# Create your views here.
class IndexView(APIView):
    def get(self, request):
        posts = BlogPost.objects.all()
        return render(request, 'index.html', context={'posts':posts, 'current_path':resolve(request.path).url_name})

class MyBlogView(APIView):
    def delete(self, request, pk, format=None):        
        posts = BlogPost.objects.filter(author=request.user)
        return render(request, 'index.html', context={'posts':posts, 'current_path':resolve(request.path).url_name})
    
    def get(self, request):
        posts = BlogPost.objects.filter(author=request.user)
        return render(request, 'index.html', context={'posts':posts, 'current_path':resolve(request.path).url_name})

class AddBlogView(APIView):
    def get(self, request):
        category = Category.objects.all()
        return render(request, 'addblog.html', context={'category': category, 'current_path':resolve(request.path).url_name})

class EditBlogView(APIView):
    def get(self, request, pk, format=None):
        post = BlogPost.objects.filter(id=pk).exists()
        if post:
            post = BlogPost.objects.filter(id=pk).first()
            category = Category.objects.all()
            return render(request, 'editblog.html', context={'post':post, 'category': category, 'current_path':resolve(request.path).url_name})
        else:
            return render(request, 'page_404.html')

class BlogDetailView(APIView):
    def get(self, request, the_slug, format=None):
        post = BlogPost.objects.filter(slug=the_slug).exists()
        if post:
            post = BlogPost.objects.filter(slug=the_slug).first()
            posts = BlogPost.objects.all()
            return render(request, 'blogdetail.html', context={'posts':posts, 'post':post, 'current_path':resolve(request.path).url_name})
        else:
            return render(request, 'page_404.html')

class UserRegistrationView(APIView):
    def post(self, request):
        serializer = UserRegistrationSerializer(data=request.data)
        if serializer.is_valid():
            user = serializer.save()
            messages.success(request, "Registration successful. You can login now." )
            return Response({"success":True}, status=201)
        return Response(serializer.errors, status=400)
    
    def get(self, request):
        return render(request, 'register.html', context={'current_path':resolve(request.path).url_name})
    
class UserLoginView(APIView):
    def post(self, request):
        serializer = UserLoginSerializer(data=request.data)
        if serializer.is_valid():
            username = serializer.validated_data['username']
            password = serializer.validated_data['password']

            user = authenticate(username=username, password=password)
            if user is not None:
                login(request=request, user=user)
                refresh = RefreshToken.for_user(user)
                messages.success(request, "You are logged in successfully." )
                response = Response()
                response.data = {'success': True, 'access_token': str(refresh.access_token), 'refresh_token':str(refresh)}
                return response
            else:
                return Response({'success': False, 'error': 'Invalid credentials.'}, status=401)
        else:
            return Response(serializer.errors, status=400)
    
    def get(self, request):
        if not request.user.is_authenticated:
            return render(request, 'login.html', context={'current_path':resolve(request.path).url_name})
        return redirect('blog:home')

def logout_view(request):
    if request.user.is_authenticated:
        logout(request)
        messages.info(request, "You have successfully logged out.") 

    return redirect('blog:login')
        

blog/templates/addblog.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Add Blog | Blog App {% endblock %}
{% block body %}
<!-- Register -->
<section class="container">
    <div class="row">
        <div class="col-md-8 my-5 mx-auto">
            <h2 class="mb-3">Add Blog</h2>
            <form action="javascript:void(0);"  id="blog-form">
                <div class="mb-3">
                    <label for="title" class="form-label">Title</label>
                    <input type="text" class="form-control" name="title" id="title">
                </div>
                <div class="mb-3">
                    <label for="subtitle" class="form-label">Sub-Title</label>
                    <input type="text" class="form-control" name="subtitle" id="subtitle">
                </div>
                <div class="mb-3">
                    <label for="slug" class="form-label">Slug</label>
                    <input type="text" class="form-control" name="slug" id="slug">
                </div>
                <div class="mb-3">
                    <label for="image" class="form-label">Image</label>
                    <input type="file" class="form-control" name="image" id="fileInput">
                </div>
                <div class="mb-3">
                    <label for="body" class="form-label">Body</label>
                    <textarea class="form-control" name="body" id="body"></textarea>
                </div>
                <div class="mb-3">
                    <label for="meta_description" class="form-label">Meta Description</label>
                    <input type="text" class="form-control" name="meta_description" id="meta_description">
                </div>
                <div class="mb-3">
                    <label for="meta_keyword" class="form-label">Meta Keywords</label>
                    <input type="text" class="form-control" name="meta_keyword" id="meta_keyword">
                </div>
                <div class="mb-3">
                    <input type="hidden" class="form-control" name="author" value="{{user.id}}" id="author">
                </div>
                <div class="mb-3">
                    <label for="tag" class="form-label">Tag</label>
                    <select name="tag" id="tag" class="form-control" multiple>
                        <option value="">Select</option>
                        {% for tag in tags %}
                            <option value="{{tag.id}}">{{tag.name}}</option>
                        {% endfor %}                       
                    </select>                   
                </div>
                <div class="mb-3">
                    <label for="category" class="form-label">Category</label>
                    <select name="category" id="category" class="form-control">
                        <option value="">Select</option>
                        {% for cat in category %}
                            <option value="{{cat.id}}">{{cat.name}}</option>
                        {% endfor %}                       
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</section>
{% endblock %}
{% block javascript %} 
<script>
    $(document).ready(function() {
        $('#blog-form').submit(function(event) {
        event.preventDefault();  // Prevent the default form submission
        const fileInput = document.getElementById('fileInput');
        // Get the form data
        var formData =  new FormData(this);
        formData.append('image', fileInput.files[0])
        console.log(formData);
        var access_token = sessionStorage.getItem('access_token');
        // Send the data via Ajax request
        $.ajax({
            url: '/api/posts/',
            type: 'POST',
            headers: {
                        "Authorization": "Bearer " + access_token
                    },
            data: formData,
            success: function(response) {
            // Handle the success response
            console.log(response);
            },
            error: function(xhr, errmsg, err) {
            // Handle the error response
            console.log(xhr.status + ': ' + xhr.responseText);
            }
        });
        });
  });
</script>
{% endblock %}

blog/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock %}</title>
    {% block meta %}{% endblock %}

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script
          src="https://code.jquery.com/jquery-3.7.0.min.js"
          integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g="
          crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar bg-dark navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'blog:home' %}">Blog App (Assignment)</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                <a class="nav-link {% if current_path == 'home' %} active {% endif %}" aria-current="page" href="{% url 'blog:home' %}">Home</a>
                </li>                                        
                {% if is_login %}
                  <li class="nav-item">
                    <a class="nav-link {% if current_path == 'myblog' %} active {% endif %}" href="{% url 'blog:myblog' %}">MyBlog</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link {% if current_path == 'addblog' %} active {% endif %}" href="{% url 'blog:addblog' %}">Add Blog</a>
                  </li>
                {% endif %}
                {% if is_login %}
                  <li class="nav-item">
                    <a class="nav-link {% if current_path == 'logout' %} active {% endif %}" href="{% url 'blog:logout' %}">Logout</a>
                  </li>
                {% else %}
                  <li class="nav-item">
                    <a class="nav-link {% if current_path == 'login' %} active {% endif %}" href="{% url 'blog:login' %}">Login</a>
                  </li>
                {% endif %} 
                <li class="nav-item">
                  <a class="nav-link {% if current_path == 'register' %} active {% endif %}" href="{% url 'blog:register' %}">Register</a>
                </li>    
            </ul>
            </div>
        </div>
    </nav>  
  {% block body %} {% endblock %}
  <footer class="bg-dark text-white text-center py-3 mt-4">
    &copy; 2023 Blog App. All rights reserved.
  </footer>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  {% block javascript %} {% endblock %}
  </body>
</html>

blog/templates/blogdetail.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{post.title}} | Blog App {% endblock %}
{% block meta %}
    <meta name="keywords" content="{{post.meta_keyword}}" />
    <meta name="description" content="{{post.meta_description}}">
	  <meta name="date" content="{{post.created_at|date:'d M, Y'}}">
    <meta name="category" content="{{post.category}}">
{% endblock %}

{% block body %}
<!-- Home Page -->
<section class="container">
<div class="row">
    <div class="container mt-4">
        <div class="row">
          <div class="col-lg-8">
            <h2>{{post.title}}</h2>
            <p>{{post.created_at}}, By {{post.author}}</p>
            <img src="{{post.image.url}}" alt="Blog Image" class="img-fluid">
            <p>{{post.subtitle}}</p>
            <p style="text-align: justify;">{{post.body}}</p>
          </div>
          <div class="col-lg-4">
            <h4>Recent Posts</h4>
            <ul class="list-group">
              {% for post in posts %}
               <a href="{% url 'blog:blogdetail' post.slug %}" style="text-decoration:none;"><li class="list-group-item">{{post.title}}</li> </a>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
</div>
</section>

{% endblock %}

blog/templates/editblog.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Edit Blog | Blog App {% endblock %}
{% block body %}
<!-- Register -->
<section class="container">
    <div class="row">
        <div class="col-md-8 my-5 mx-auto">
            <div class="row">
                <img src="{{post.image.url}}" alt="">
            </div>
            <h2 class="my-3">Edit Blog</h2>
            <form action="javascript:void(0);"  id="blog-form">
                <div class="mb-3">
                    <label for="title" class="form-label">Title</label>
                    <input type="text" class="form-control" value="{{post.title}}" name="title" maxlength="200" id="title">
                </div>
                <div class="mb-3">
                    <label for="subtitle" class="form-label">Sub-Title</label>
                    <input type="text" class="form-control" name="subtitle" value="{{post.subtitle}}"  maxlength="250" id="subtitle">
                </div>
                <div class="mb-3">
                    <label for="slug" class="form-label">Slug</label>
                    <input type="text" class="form-control" name="slug" value="{{post.slug}}"  maxlength="250" id="slug">
                </div>
                <div class="mb-3">
                    <label for="image" class="form-label">Image</label>
                    <input type="file" class="form-control" name="image"  id="fileInput">
                </div>
                <div class="mb-3">
                    <label for="body" class="form-label">Body</label>
                    <textarea class="form-control" name="body" id="body" style="height: 266px;">{{post.body}}</textarea>
                </div>
                <div class="mb-3">
                    <label for="meta_description" class="form-label">Meta Description</label>
                    <input type="text" class="form-control" name="meta_description" value="{{post.meta_description}}"  maxlength="150" id="meta_description">
                </div>
                <div class="mb-3">
                    <label for="meta_keyword" class="form-label">Meta Keywords</label>
                    <input type="text" class="form-control" name="meta_keyword" maxlength="150" value="{{post.meta_keyword}}"  id="meta_keyword">
                </div>
                <div class="mb-3">
                    <input type="hidden" class="form-control" name="author" value="{{user.id}}" id="author">
                </div>
                <div class="mb-3">     
                    {{post.category}}       
                    <label for="category" class="form-label">Category</label>
                    <select name="category" id="category" class="form-control">
                        <option value="">Select</option>
                        {% for cat in category %}
                            {% if cat.name == post.category.name %}
                            <option value="{{cat.id}}" selected>{{cat.name}}</option>
                            {% else %}
                            <option value="{{cat.id}}">{{cat.name}}</option>
                            {% endif %}
                        {% endfor %}                       
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</section>
{% endblock %}
{% block javascript %} 
<script>
    $(document).ready(function() {
        $('#blog-form').submit(function(event) {
        event.preventDefault();  
        const fileInput = document.getElementById('fileInput');
        // Get the form data
        var formData =  new FormData(this);
        if(fileInput.files[0]){
            formData.append('image', fileInput.files[0])
        }else{
            formData.append('image', '')
        }
        var access_token = sessionStorage.getItem('access_token');
        // Send the data via Ajax request
        $.ajax({
            url: '/api/posts/'+'{{post.id}}'+'/',
            type: 'PUT',
            processData: false,
            contentType: false,
            headers: {
                        "Authorization": "Bearer " + access_token
                    },
            data: formData,
            success: function(response, status, xhr) {
                if(xhr.status == 200){
                    alert("Blog Edited Successfully.")
                    window.location.href = '/my-blog/'
                }
            },
            error: function(xhr, errmsg, err) {
                // Handle the error response
                if(xhr.status == 400){
                    alert("Please check form fields")
                }
                if(xhr.status == 401){
                    alert("Unauthorised.")    
                    window.location.href = '/login/';                   
                }
                if(xhr.status == 500){
                    alert("Internal server error.")                    
                }
            }
        });
        });
  });
</script>
{% endblock %}

blog/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Index | Blog App {% endblock %}
{% block body %}
<!-- Home Page -->
<section class="container">
    <div class="row">
        <div class="col-md-8 my-2 mx-auto">
          {% for message in messages %}
          <div class="alert alert-primary mt-2 " role="alert">
              {{message}}
          </div>
          {% endfor %}
        </div>
    </div>
</section>
<section class="container">
<div class="row">
    {% if posts %}
        {% for post in posts %}
        <div class="col-md-4 my-2">            
            <div class="card" style="">
                <img src="{{post.image.url}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <a href="{% url 'blog:blogdetail' post.slug %}" style="text-decoration:none;"><h5 class="card-title text-dark">{{post.title}}</h5></a>
                    <p><strong>by {{post.author}}</strong></p>
                    <p class="card-text"> {{post.subtitle |truncatewords:"50" }}</p>
                    <div class="{% if current_path == 'myblog' %} d-flex {% endif %}">
                        <a href="{% url 'blog:blogdetail' post.slug %}" class="btn btn-primary m-auto">Read more</a>
                        {% if current_path == 'myblog' %}
                        <a href="javascript:void(0);" onclick="deletePost('{{post.id}}')" class="btn btn-primary m-auto">Delete</a>
                        <a href="{% url 'blog:editblog' post.id %}" class="btn btn-primary m-auto">Edit</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    {% else %}
        <div class="alert alert-primary mt-2 " role="alert">
            No Blog posted yet. 
        </div>
    {% endif %}
    
</div>
</section>
{% endblock %}

{% block javascript %} 
<script>
    function getAccessTokenAfterTokenExpire(){
        var refresh_token = sessionStorage.getItem('refresh_token');
        $.ajax({
            type : "POST",
            url : "/token/refresh/",
            data : {'refresh' : refresh_token},
            success : function(response, status, xhr) {                     
                if(xhr.status == 200){ 
                    // console.log(response);
                    sessionStorage.setItem('access_token', response.access);
                }else{
                    alert("Something went wrong.")
                }
            },
            error: function(xhr, errmsg, err) {
                alert("Something went wrong.")
            }    
        })
    }
    

    function deletePost(id){ 
        if (confirm("Are you sure you want delete Post!")) {
            var access_token = sessionStorage.getItem('access_token');
            $.ajax({
                type : "DELETE",
                url : "/api/posts/"+id,
                headers: {
                        "Authorization": "Bearer " + access_token
                    },
                data : {},
                success : function(response, status, xhr) {     
                    if(xhr.status == 204){ 
                        alert("Post Deleted Successfully.")   
                        window.location.href = '/my-blog/';
                    }else{
                        alert("Something went wrong.")
                    }
                },
                error: function(xhr, errmsg, err) {
                    if(xhr.status == 400){
                        alert(JSON.parse(xhr.responseText).non_field_errors)
                    }
                    if(xhr.status == 401){
                        alert(JSON.parse(xhr.responseText).error)    
                        window.location.href = '/login/';                   
                    }
                    if(xhr.status == 500){
                        alert("Internal server error.")          
                    }
                }                        
            });
        }       
       
    }
</script>
{% endblock %}

blog/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Login | Blog App {% endblock %}
{% block body %}
<!-- Login -->
<section class="container">
<div class="row">
    <div class="col-md-8 my-5 mx-auto">
        <h2 class="mb-3">Login</h2>
        <form action="javascript:void(0);" method="#">
            <div class="mb-3">
                <label for="exampleInputUsername" class="form-label">Username</label>
                <input type="text" class="form-control" id="exampleInputUsername">
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Password</label>
                <input type="password" class="form-control" id="exampleInputPassword1">
            </div>
            <button type="submit" onclick="userLogin()" class="btn btn-primary">Submit</button>          
        </form>
        {% for message in messages %}
        <div class="alert alert-primary mt-2 " role="alert">
            {{message}}
        </div>
        {% endfor %}
    </div>
</div>
</section>    
{% endblock %}
{% block javascript %} 
<script>
    function userLogin(){        
        $.ajax({
            type : "POST",
            url : "/login/",
            data : {'username' : $('#exampleInputUsername').val(), 'password': $('#exampleInputPassword1').val()},
            success : function(response) {     
                console.log(response.data);
                if(response.success == true){ 
                    sessionStorage.setItem('access_token', response.access_token);
                    sessionStorage.setItem('refresh_token', response.refresh_token);    
                    window.location.href = '/';
                }else{
                    alert(response)
                }
            },
            error: function(xhr, errmsg, err) {
                if(xhr.status == 400){
                    alert(JSON.parse(xhr.responseText).non_field_errors)
                }
                if(xhr.status == 401){
                    alert(JSON.parse(xhr.responseText).error)
                }
                if(xhr.status == 500){
                    alert("Internal server error.")          
                }
            }                        
        });
    }
</script>
{% endblock %}

blog/templates/page_404.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Page Not Found</title>
  <style></style>
</head>
<body>
  <div class="container">
    <h1>Page Not Found</h1>
    <p>The page you are looking for could not be found. Please check the URL or go back to the <a href="{% url 'blog:home' %}" class="home-link">Home Page</a>.</p>
    <div class="footer">
      <p>© 2023 BlogApp. All rights reserved.</p>
    </div>
  </div>
</body>
</html>

blog/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Register | Blog App {% endblock %}
{% block body %}
<!-- Register -->
<section class="container">
    <div class="row">
        <div class="col-md-8 my-5 mx-auto">
            <h2 class="mb-3">Register</h2>
            <form action="javascript:void(0);">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="exampleInputUsername" class="form-label">Username</label>
                    <input type="text" class="form-control" id="exampleInputUsername" aria-describedby="emailHelp" required>
                </div>
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Email address</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" required>
                    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
                </div>
                <div class="mb-3">
                    <label for="exampleInputPassword1" class="form-label">Password</label>
                    <input type="password" class="form-control" id="exampleInputPassword1" required>
                </div>
                <div class="mb-3">
                    <label for="exampleInputPassword2" class="form-label">Confirm Password</label>
                    <input type="password" class="form-control" id="exampleInputPassword2" required>
                </div>
                <button type="submit" onclick="userRegistration();" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</section>
{% endblock %}
{% block javascript %} 
<script>
    function userRegistration(){        
        $.ajax({
            type : "POST",
            url : "/register/",
            data : {'csrfmiddlewaretoken':$("input[name='csrfmiddlewaretoken']").val(), 'username' : $('#exampleInputUsername').val(), 'email': $('#exampleInputEmail1').val(), 'password1': $('#exampleInputPassword1').val(), 'password2': $('#exampleInputPassword2').val()},
            success : function(response) {     
                if(response.success == true){     
                     window.location.href = '/login/';
                }else{
                    alert("Something went wrong.")
                }
            },
            error: function(xhr, errmsg, err) {
                alert(JSON.parse(xhr.responseText).non_field_errors)
            }                        
        });
    }
</script>
{% endblock %}